---
- hosts: webserver
  become: yes
  become_user: root
  gather_facts: no
  tasks:
    - name: install telenet and lynx
      yum: pkg={{ item }} state=latest
      with_items:
        - telnet
        - lynx
      tags:
        - packages
    - name: verify packages installed
      raw: yum list installed |grep telnet > /home/ansible/pkg.log
      tags:
       - verification  

