---
- hosts: webserver
  become: yes
  become_user: root
  gather_facts: no
  vars_files:
    - variable/variable.yml
  tasks:
    - include: packages/packages.yml
    - include: commands/commands.yml
  handlers:
    - include: handler/handler.yml

